  # This is a basic workflow to help you get started with Actions

name: NDepend-DailyBuildAnalyis-Results

       # Controls when the workflow will run
on:
  # Triggers the workflow on every midnight
  schedule:
    - cron: "*/2 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a PowerShell script
        shell: pwsh
        run: D:\NDependDailyBuild.ps1
