name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: cd D:\Znode-Baseline-Build
      - run: git pull D:/Znode-Baseline-Build/.git/
      - run: cd D:\Znode-Latest-Build
      - run: git pull D:\Znode-Latest-Build/.git/
      - run: cd D:\Ndepend
      - run: NDepend.Console.exe "D:\Znode-Latest-Build\Projects\Znode.Multifront.ndproj"
